---
abstract: 'Interface to Rackspace CloudFiles service'
author:
  - 'Fork by Christiaan Kras <ckras@cpan.org>'
  - 'Christiaan Kras <ckras@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Stat: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Rackspace-CloudFiles
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::SSLeay: 0
  Data::Stream::Bulk: 0
  DateTime::Format::HTTP: 0.39
  Digest::MD5: 0
  Digest::MD5::File: 0
  File::Slurp: 0
  JSON::XS::VersionOneAndTwo: 0
  LWP: 0
  LWP::ConnCache::MaxKeepAliveRequests: 0
  LWP::UserAgent::Determined: 0
  Moose: 0
  MooseX::StrictConstructor: 0
  perl: 5.8.8
resources:
  bugtracker: http://github.com/Htbaa/WebService-Rackspace-CloudFiles/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Htbaa/WebService-Rackspace-CloudFiles
version: 1.01
